import { z } from 'zod'

export const ICON_NAMES = [
  'inbox',
  'kanban-square',
  'table-2',
  'calendar',
  'gantt-chart',
  'list-checks',
  'house',
  'message-circle',
  'square-check-big',
  'layout-grid',
  'star',
  'plus',
  'settings',
  'search',
  'bell',
  'user',
  'users',
  'folder',
  'file',
  'tag',
  'flag',
  'bookmark',
  'pin',
  'archive',
  'trash',
  'circle',
  'check-circle',
  'alert-circle',
  'help-circle',
  'info',
  'lightbulb',
  'rocket',
  'zap',
  'activity',
  'bar-chart',
  'pie-chart',
  'trending-up',
  'clock',
  'history',
  'hash',
  'at-sign',
  'mail',
  'send',
  'paperclip',
  'link',
  'globe',
  'lock',
  'unlock',
  'eye',
  'eye-off',
  'filter',
  'sliders',
  'menu',
  'more-horizontal',
  'chevron-right',
  'chevron-down',
] as const

export const IconNameSchema = z.enum(ICON_NAMES)
export type IconName = z.infer<typeof IconNameSchema>
