extend type Query {
  me: Member
}

extend type Mutation {
  login(input: LoginInput!): LoginPayload
  logout(input: LogoutInput!): Boolean
}

type AuthTokenPair {
  accessToken: String!
  refreshToken: String!
  accessTokenExpiresAt: DateTime!
  refreshTokenExpiresAt: DateTime!
}

type LoginPayload {
  member: Member!
  tokens: AuthTokenPair!
}

input LoginInput {
  email: String!
  password: String!
}

input RefreshTokenInput {
  refreshToken: String!
}

input LogoutInput {
  refreshToken: String!
}
