type Query {
  members(page: Int!, size: Int!): MemberPage!
  member(id: Long!): Member
}

type Mutation {
  registerMember(input: RegisterMemberInput!): Member!
  updateMember(input: UpdateMemberInput!): Member!
}

type Member {
  id: Long!
  name: String!
  email: String!
  authorities: [Authority!]!
  isEnabled: Boolean!
  createdDatetime: DateTime!
}

type MemberPage {
  members: [Member!]!
  pageInfo: PageInfo!
}

input RegisterMemberInput {
  name: String!
  email: String!
  password: String!
  isEnabled: Boolean!
  teamId: Long
  authorityIds: [Int!]!
}

input UpdateMemberInput {
  id: Long!
  name: String
  email: String
  isEnabled: Boolean
  authorityIds: [Int!]
}
