type Query {
  members(page: Int!, size: Int!): MemberPage!
  member(id: Long!): Member
}

type Mutation {
  registerMember(input: RegisterMemberInput!): Member
  updateMember(input: UpdateMemberInput!): Member
}

type Member {
  id: Long!
  name: String!
  email: String!
  isAdmin: Boolean!
  isEnabled: Boolean!
  createdDatetime: DateTime!
}

type MemberPage {
  members: [Member!]!
  pageInfo: PageInfo!
}

input RegisterMemberInput {
  name: String!
  email: String!
  password: String!
  teamId: Long!
}

input UpdateMemberInput {
  id: Long!
  name: String
  email: String
  isAdmin: Boolean
  isEnabled: Boolean
}
