extend type Query {
  teams(page: Int!, size: Int!): TeamPage!
  team(id: Long!): Team
}

extend type Mutation {
  createTeam(input: CreateTeamInput!): Team
  updateTeam(input: UpdateTeamInput!): Team
  deleteTeam(input: DeleteTeamInput!): Boolean

  addTeamMember(input: AddTeamMemberInput!): TeamMember
  removeTeamMember(input: RemoveTeamMemberInput!): TeamMember
}

type Team {
  id: Long!
  name: String!
  createdDatetime: DateTime!
  members: [Member!]!
}

type TeamPage {
  teams: [Team!]!
  pageInfo: PageInfo!
}

type TeamMember {
  team: Team
  member: Member
}

input CreateTeamInput {
  name: String!
}

input UpdateTeamInput {
  id: Long!
  name: String!
}

input DeleteTeamInput {
  id: Long!
}

input AddTeamMemberInput {
  teamId: Long!
  memberId: Long!
}

input RemoveTeamMemberInput {
  teamId: Long!
  memberId: Long!
}
