import type { Issue, Label, User } from './types'

const users: User[] = [
  { id: 'u_1', name: 'Jaesang Lee' },
  { id: 'u_2', name: 'Mina Park' },
  { id: 'u_3', name: 'Daniel Cho' },
  { id: 'u_4', name: 'Sunwoo Han' },
  { id: 'u_5', name: 'Yujin Kim' },
]

const labels: Label[] = [
  { id: 'l_1', name: 'frontend', color: '#3b82f6' },
  { id: 'l_2', name: 'backend', color: '#10b981' },
  { id: 'l_3', name: 'design', color: '#d946ef' },
  { id: 'l_4', name: 'bug', color: '#ef4444' },
  { id: 'l_5', name: 'epic', color: '#8b5cf6' },
  { id: 'l_6', name: 'docs', color: '#f59e0b' },
]

const day = (offset: number) => {
  const d = new Date()
  d.setDate(d.getDate() + offset)
  return d.toISOString()
}

export const mockUsers = users
export const mockLabels = labels

export const mockIssues: Issue[] = [
  {
    id: 'iss_001',
    key: 'DSH-101',
    title: 'Wire Relay environment to context-api endpoint',
    description: 'Replace placeholder schema with introspection from context-api once issues land.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignees: [users[0], users[2]],
    labels: [labels[0], labels[1]],
    reporter: users[0],
    dueAt: day(2),
    createdAt: day(-3),
    updatedAt: day(-1),
    projectKey: 'DSH',
  },
  {
    id: 'iss_002',
    key: 'DSH-102',
    title: 'Design issue detail drawer (Notion-style)',
    status: 'IN_REVIEW',
    priority: 'MEDIUM',
    assignees: [users[1]],
    labels: [labels[2]],
    reporter: users[1],
    dueAt: day(5),
    createdAt: day(-5),
    updatedAt: day(-1),
    projectKey: 'DSH',
  },
  {
    id: 'iss_003',
    key: 'DSH-103',
    title: 'Kanban: optimistic move + persisted orderKey',
    description: 'Drag-drop should update local cache before server confirmation.',
    status: 'TODO',
    priority: 'URGENT',
    assignees: [users[0]],
    labels: [labels[0], labels[4]],
    reporter: users[2],
    dueAt: day(1),
    createdAt: day(-2),
    updatedAt: day(-1),
    projectKey: 'DSH',
  },
  {
    id: 'iss_004',
    key: 'DSH-104',
    title: 'Add command palette (⌘K) with fuzzy search',
    status: 'BACKLOG',
    priority: 'LOW',
    assignees: [],
    labels: [labels[0]],
    reporter: users[3],
    createdAt: day(-7),
    updatedAt: day(-7),
    projectKey: 'DSH',
  },
  {
    id: 'iss_005',
    key: 'DSH-105',
    title: 'Calendar view: month / week toggle',
    status: 'BACKLOG',
    priority: 'MEDIUM',
    assignees: [users[4]],
    labels: [labels[0], labels[2]],
    reporter: users[4],
    dueAt: day(14),
    createdAt: day(-10),
    updatedAt: day(-2),
    projectKey: 'DSH',
  },
  {
    id: 'iss_006',
    key: 'DSH-106',
    title: 'Fix avatar fallback in dark mode',
    status: 'DONE',
    priority: 'LOW',
    assignees: [users[1]],
    labels: [labels[3]],
    reporter: users[1],
    createdAt: day(-12),
    updatedAt: day(-1),
    projectKey: 'DSH',
  },
  {
    id: 'iss_007',
    key: 'DSH-107',
    title: 'Electron auto-update via Forge publishers',
    status: 'BACKLOG',
    priority: 'HIGH',
    assignees: [users[2]],
    labels: [labels[5]],
    reporter: users[0],
    createdAt: day(-4),
    updatedAt: day(-4),
    projectKey: 'DSH',
  },
  {
    id: 'iss_008',
    key: 'DSH-108',
    title: 'Standalone web build behind nginx',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assignees: [users[0]],
    labels: [labels[5]],
    reporter: users[0],
    dueAt: day(3),
    createdAt: day(-2),
    updatedAt: day(0),
    projectKey: 'DSH',
  },
  {
    id: 'iss_009',
    key: 'DSH-109',
    title: 'Investigate flaky relay-compiler watch on macOS',
    status: 'CANCELLED',
    priority: 'NO_PRIORITY',
    assignees: [],
    labels: [labels[3]],
    reporter: users[3],
    createdAt: day(-20),
    updatedAt: day(-15),
    projectKey: 'DSH',
  },
  {
    id: 'iss_010',
    key: 'DSH-110',
    title: 'Sidebar tree: drag to reorder projects',
    status: 'TODO',
    priority: 'LOW',
    assignees: [users[4], users[1]],
    labels: [labels[2]],
    reporter: users[4],
    createdAt: day(-1),
    updatedAt: day(-1),
    projectKey: 'DSH',
  },
]
