import type { IconName } from '@dashway/app-protocol'
import {
  Activity,
  AlertCircle,
  Archive,
  AtSign,
  BarChart,
  Bell,
  Bookmark,
  Calendar,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Circle,
  Clock,
  Eye,
  EyeOff,
  File,
  Filter,
  Flag,
  Folder,
  GanttChart,
  Globe,
  Hash,
  HelpCircle,
  History,
  House,
  Inbox,
  Info,
  KanbanSquare,
  LayoutGrid,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  type LucideIcon,
  Mail,
  Menu,
  MessageCircle,
  MoreHorizontal,
  Paperclip,
  PieChart,
  Pin,
  Plus,
  Rocket,
  Search,
  Send,
  Settings,
  Sliders,
  SquareCheckBig,
  Star,
  Table2,
  Tag,
  Trash,
  TrendingUp,
  Unlock,
  User,
  Users,
  Zap,
} from '@dashway/ui/icons'

const iconMap: Record<IconName, LucideIcon> = {
  inbox: Inbox,
  'kanban-square': KanbanSquare,
  'table-2': Table2,
  calendar: Calendar,
  'gantt-chart': GanttChart,
  'list-checks': ListChecks,
  house: House,
  'message-circle': MessageCircle,
  'square-check-big': SquareCheckBig,
  'layout-grid': LayoutGrid,
  star: Star,
  plus: Plus,
  settings: Settings,
  search: Search,
  bell: Bell,
  user: User,
  users: Users,
  folder: Folder,
  file: File,
  tag: Tag,
  flag: Flag,
  bookmark: Bookmark,
  pin: Pin,
  archive: Archive,
  trash: Trash,
  circle: Circle,
  'check-circle': CheckCircle,
  'alert-circle': AlertCircle,
  'help-circle': HelpCircle,
  info: Info,
  lightbulb: Lightbulb,
  rocket: Rocket,
  zap: Zap,
  activity: Activity,
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  clock: Clock,
  history: History,
  hash: Hash,
  'at-sign': AtSign,
  mail: Mail,
  send: Send,
  paperclip: Paperclip,
  link: Link,
  globe: Globe,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  'eye-off': EyeOff,
  filter: Filter,
  sliders: Sliders,
  menu: Menu,
  'more-horizontal': MoreHorizontal,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
}

export function resolveIcon(name: string): LucideIcon | null {
  return (iconMap as Record<string, LucideIcon | undefined>)[name] ?? null
}
