server.port: 12001

spring:
  application:
    name: ${DASHWAY_APP_NAME:chat}

  graphql:
    http:
      path: /${DASHWAY_APP_NAME:chat}/graphql

  datasource:
    driver-class-name: org.postgresql.Driver
    username: context_api
    password: context_api
    url: jdbc:postgresql://localhost:5432/dashway

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

chat:
  context-api:
    base-url: http://localhost:8080

logging:
  level:
    root: info
