version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: issue-tracker-backend:local
    container_name: issue-tracker-backend
    restart: unless-stopped
    ports:
      - 12000:8080