export const EMOJI_MAP: Record<string, string> = {
  smile: '😄',
  grin: '😁',
  joy: '😂',
  laughing: '😆',
  wink: '😉',
  heart: '❤️',
  thumbsup: '👍',
  thumbsdown: '👎',
  fire: '🔥',
  rocket: '🚀',
  tada: '🎉',
  eyes: '👀',
  thinking: '🤔',
  cry: '😢',
  sob: '😭',
  sweat: '😅',
  shrug: '🤷',
  wave: '👋',
  clap: '👏',
  ok: '👌',
}
